set(ITK_PACKAGE_VERSION 4.0)
set(ITK_REPO_URL https://github.com/eile/ITK.git)
set(ITK_REPO_TAG release)
set(ITK_OPTIONAL ON)
set(ITK_CMAKE_INCLUDE "SYSTEM")

set(ITK_CMAKE_ARGS -DITK_USE_SYSTEM_HDF5=ON
  -DITK_MODULE_ITKIOHDF5_EXCLUDE_FROM_DEFAULT=ON
  -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF
  -DCMAKE_CXX_FLAGS=${COMMON_CXXSTD_FLAGS})
set(ITK_FORCE_BUILD ON)
