set(LIBZMQ_PACKAGE_VERSION 4)
set(LIBZMQ_OPTIONAL ON)
set(LIBZMQ_REPO_URL https://github.com/zeromq/zeromq4-x.git)
set(LIBZMQ_SOURCE "${CMAKE_SOURCE_DIR}/src/libzmq")
set(LIBZMQ_DEB_NAME libzmq3-dev)
set(LIBZMQ_PORT_NAME zmq-devel)
